#!/bin/sh

# immediately exit when error occurs
set -e

usage() {
	echo "usage: miner [-h] {factory_reset,run_recovery,fault_light} ..."
	echo
	echo "positional arguments:"
	echo "  {factory_reset,run_recovery,fault_light}"
	echo "    factory_reset       reboot and initiate factory reset"
	echo "    run_recovery        reboot to recovery mode"
	echo "    fault_light         turn on or off miner's fault LED"
	echo
	echo "optional arguments:"
	echo "  -h, --help            show this help message and exit"
}

factory_reset() {
	exec bos factory_reset "$@"
}

run_recovery() {
	exec bos run_recovery "$@"
}

fault_light() {
	if [ $# -ne 1 -o \( "$1" != 'on' -a "$1" != 'off' \) ]; then
		echo "command 'fault_light' takes only one argument [on|off]"
		exit 1
	fi
	# send 'on' or 'off' to cgminer_monitor
	echo $1 | nc localhost 4029 >/dev/null
}

# check number of arguments
if [ $# -lt 1 ]; then
	echo "missing command argument"
	exit 1
fi

# try to find command
command="$1"

case $command in
	factory_reset|run_recovery|fault_light)
		shift
		$command "$@"
	;;
	-h|--help)
		usage
	;;
	*)  # unknown command
		echo "unknown command '$command'"
		exit 1
	;;
esac
